// Package contracts defines the shared event and API types used across all services.
// All inter-service communication is based on these types.
package contracts

import "time"

// ---- Incident and detection ----

// SeverityLevel represents the assessed severity of an incident.
type SeverityLevel string

const (
	SeverityCritical SeverityLevel = "critical"
	SeverityHigh     SeverityLevel = "high"
	SeverityMedium   SeverityLevel = "medium"
	SeverityLow      SeverityLevel = "low"
)

// IncidentEvent is emitted by the anomaly detection layer when a fault is detected.
type IncidentEvent struct {
	ID         string            `json:"id"`
	Scenario   string            `json:"scenario"` // e.g. "bad-rollout", "resource-saturation", "batch-timeout"
	Service    string            `json:"service"`
	Namespace  string            `json:"namespace"`
	Severity   SeverityLevel     `json:"severity"`
	DetectedAt time.Time         `json:"detected_at"`
	Evidence   []EvidenceItem    `json:"evidence"`
	Labels     map[string]string `json:"labels,omitempty"`
}

// EvidenceItem is a single signal datum supporting an incident or RCA.
type EvidenceItem struct {
	Source    string    `json:"source"` // "metrics", "logs", "events"
	Signal    string    `json:"signal"` // e.g. "cpu_usage_percent", "pod_restart_count"
	Value     string    `json:"value"`
	Timestamp time.Time `json:"timestamp"`
}

// ---- RCA ----

// RCAPayload is the output of the AI diagnosis engine for a given incident.
type RCAPayload struct {
	IncidentID         string         `json:"incident_id"`
	Summary            string         `json:"summary"`          // human-readable RCA from LLM
	RootCause          string         `json:"root_cause"`       // short label
	ConfidenceScore    float64        `json:"confidence_score"` // 0.0 to 1.0
	SupportingEvidence []EvidenceItem `json:"supporting_evidence"`
	GeneratedAt        time.Time      `json:"generated_at"`
}

// ---- Remediation ----

// RiskLevel describes the assessed blast radius of a remediation action.
type RiskLevel string

const (
	RiskLow    RiskLevel = "low"
	RiskMedium RiskLevel = "medium"
	RiskHigh   RiskLevel = "high"
)

// RemediationAction is a proposed fix for an incident, generated by the diagnosis engine
// and executed (after approval) by the orchestrator.
type RemediationAction struct {
	ID          string            `json:"id"`
	IncidentID  string            `json:"incident_id"`
	RunbookName string            `json:"runbook_name"` // e.g. "rollback-deployment"
	Description string            `json:"description"`
	Risk        RiskLevel         `json:"risk"`
	Params      map[string]string `json:"params"` // e.g. {"namespace": "default", "deployment": "sample-app"}
	CreatedAt   time.Time         `json:"created_at"`
}

// ApprovalStatus tracks whether a remediation action has been approved or rejected.
type ApprovalStatus string

const (
	ApprovalPending  ApprovalStatus = "pending"
	ApprovalApproved ApprovalStatus = "approved"
	ApprovalRejected ApprovalStatus = "rejected"
)

// RemediationRequest wraps a RemediationAction with approval state.
type RemediationRequest struct {
	Action    RemediationAction `json:"action"`
	Approval  ApprovalStatus    `json:"approval"`
	UpdatedAt time.Time         `json:"updated_at"`
}

// RemediationResult is the outcome of executing a remediation action.
type RemediationResult struct {
	ActionID    string     `json:"action_id"`
	IncidentID  string     `json:"incident_id"`
	Success     bool       `json:"success"`
	Message     string     `json:"message"`
	ExecutedAt  time.Time  `json:"executed_at"`
	RecoveredAt *time.Time `json:"recovered_at,omitempty"`
}

// ---- Audit ----

// AuditEntry records a significant event in the incident lifecycle.
type AuditEntry struct {
	ID         string    `json:"id"`
	IncidentID string    `json:"incident_id"`
	Actor      string    `json:"actor"` // "system" or "operator"
	Event      string    `json:"event"` // e.g. "incident_detected", "rca_generated", "action_approved", "action_executed"
	Detail     string    `json:"detail"`
	Timestamp  time.Time `json:"timestamp"`
}

// ---- Incident pipeline status ----

// IncidentStatus represents the pipeline stage of an incident.
type IncidentStatus string

const (
	StatusDetected         IncidentStatus = "detected"
	StatusAnalyzing        IncidentStatus = "analyzing"
	StatusAwaitingApproval IncidentStatus = "awaiting_approval"
	StatusRemediating      IncidentStatus = "remediating"
	StatusResolved         IncidentStatus = "resolved"
	StatusFailed           IncidentStatus = "failed"
)

// IncidentStatusUpdate records the current pipeline stage of an incident.
type IncidentStatusUpdate struct {
	IncidentID string         `json:"incident_id"`
	Status     IncidentStatus `json:"status"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// ---- KPI ----

// KPISnapshot holds the before/after performance metrics for a resolved incident.
type KPISnapshot struct {
	IncidentID         string        `json:"incident_id"`
	MTTD               time.Duration `json:"mttd"` // mean time to detect
	MTTR               time.Duration `json:"mttr"` // mean time to recover
	AutoResolved       bool          `json:"auto_resolved"`
	EstimatedCostSaved float64       `json:"estimated_cost_saved_usd"`
}
