apiVersion: v1
kind: Namespace
metadata:
  name: workloads
  labels:
    app.kubernetes.io/managed-by: ravi-poc
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: ravi-poc
